#define SYS_OPEN 0
#define SYS_CLOSE 1
#define SYS_WRITE 2
#define SYS_READ 3
#define SYS_MMAP 4
#define SYS_RANDOMFILL 5
#define SYS_LSEEK 6
#define SYS_FSTAT 7
#define SYS_FORK 8
#define SYS_EXEC 9
#define SYS_DUP2 10
#define SYS_PIPE 11
#define SYS_KPOLL 12
#define SYS_EXIT 13
#define SYS_WAITFD 14
#define SYS_GETCWD 15
#define SYS_CHDIR 16
#define SYS_FCNTL 17
#define SYS_GETDENT 18
